### ISSUE TITLE
Is this being actively developed?

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-external-task-client-spring-boot#1]

**Comment by falko** [comment]
Would you like to contribute?

**Comment by rfelgent** [comment]
@falko , I would like to ask the question differently: 

Are you camunda guys keen on supporting "camel-camunda" (external task client is covered) or "spring-boot-external-task-client"... or both ?

greetings

**Comment by falko** [comment]
Both are community projects. Therefore none of them are supported as part of the enterprise edition and whichever project gains contributions from the community will stay alive.

**Comment by rfelgent** [comment]
Hi  @falko , 

FYI

I had a quick look into "camel-camunda" project. As far as I understand the code base, the external-task endpoint requires Camunda's ProcessEngine - something I do not want to have as dependency in my client (https://forum.camunda.org/t/camel-camunda-integration/13814/2).

Therefore, I will hava a look at this project.

Thank you

**Comment by falko** [comment]
Great!
